# Generated by Django 3.1.1 on 2020-09-01 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_auto_20200719_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='todolist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todos', to='todoapp.todolist'),
        ),
    ]
